name: new_messenger
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pocketbase: ^0.23.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_webrtc: ^1.3.0
  app_links: ^7.0.0
  url_launcher: ^6.3.1
  local_notifier: ^0.1.5
  file_picker: ^10.3.10
  audioplayers: ^6.5.1
  window_manager: ^0.5.1
  flutter_background: ^1.2.1
  crypto: ^3.0.3
  # ... твои текущие пакеты ...
  livekit_client: ^2.6.3
  dart_jsonwebtoken: ^3.3.1
  permission_handler: ^11.3.0
  flutter_v2ray: ^1.0.10
  dio: ^5.9.1
  path_provider: ^2.1.5
  wakelock_plus: ^1.2.8
  open_filex: ^4.7.0
  floating: ^6.0.0
  file_saver: ^0.2.0    # Для выбора папки при сохранении файлов
  video_player: ^2.8.0  # Для воспроизведения видео прямо в чате
  record: ^6.2.0
  path: ^1.9.1
  tray_manager: ^0.5.2
  flutter_riverpod: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/sounds/Ring.mp3
    - assets/proxies.json
    - assets/sounds/bel.mp3
    - assets/sounds/DialTone.mp3
    - assets/sounds/mes.mp3